#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   Displays "FizzBuzz" when the number is a multiple of 3 and 5.
#   Displays "Fizz" when the number is a multiple of 3.
#   Displays "Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

number=1

while [ $number -lt 100 ]
do
	if (( number % 3 == 0 && number % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( number % 3 == 0 ))
	then
		echo "Fizz"
	elif (( number % 5 == 0 ))
		echo "Buzz"
	else
		echo "$number"
	fi
	(( number++ ))
done
