#!/usr/bin/env bash
# Displays "Best School" 9 times using an while loop.
# On the 9th iteration, displays "Hi" before "Best School"..

count=0

while [ $count -lt 10 ]
do
	if [ $count -lt 9 ]
	then
		echo "Best School"
	else
		echo "Hi"
	fi

        (( count++ ))
done
