#!/usr/bin/env bash
# Displays information about the file `school`.

FILE=school

if [ -f "$FILE" ]; then
	echo "$FILE file exists"
	if [ -s "$FILE" ]; then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	echo "$FILE is a regular file"
else
	echo "$FILE file does not exist"
fi
